all:
	@if [ `id -u` -ne 0 ]; then \
		echo "You need to be root to run this Makefile" >&2; \
		exit 1; \
	fi
# install required libraries
	sudo apt-get install libx11-dev;
# giving access to input files to get the mouse wheel direction
	sudo chmod -R 777 /dev/input;
# compile the program
	./build/compile_linux_version.sh;
	cp -f ejib /usr/bin;